import { jsPDF } from 'jspdf';


export const generateQuotationPDF = (data) => {
  const { quotationItems, warrantyDetails, productionDetails, totals } = data;
  
  const doc = new jsPDF();
  let yPos = 20;

  // Header
  doc.setFillColor(37, 99, 235); // Blue color
  doc.rect(0, 0, 210, 40, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(24);
  doc.setFont('helvetica', 'bold');
  doc.text('SOLAR QUOTATION', 105, 20, { align: 'center' });
  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  doc.text('Professional Solar Installation Quote', 105, 30, { align: 'center' });
  
  // Reset text color
  doc.setTextColor(0, 0, 0);
  yPos = 50;

  // Date
  doc.setFontSize(10);
  doc.text(`Generated: ${new Date().toLocaleDateString('en-US', { 
    year: 'numeric', 
    month: 'long', 
    day: 'numeric' 
  })}`, 20, yPos);
  yPos += 15;

  // Quotation Items Section
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text('QUOTATION ITEMS', 20, yPos);
  yPos += 8;
  doc.setLineWidth(0.5);
  doc.line(20, yPos, 190, yPos);
  yPos += 10;

  // Table Header
  doc.setFontSize(9);
  doc.setFont('helvetica', 'bold');
  doc.text('Sr.', 20, yPos);
  doc.text('Description', 30, yPos);
  doc.text('Brand', 90, yPos);
  doc.text('Model', 120, yPos);
  doc.text('Qty', 145, yPos);
  doc.text('Rate (PKR)', 160, yPos);
  doc.text('Amount (PKR)', 180, yPos, { align: 'right' });
  yPos += 5;
  doc.setLineWidth(0.3);
  doc.line(20, yPos, 190, yPos);
  yPos += 6;

  // Table Rows
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  quotationItems.forEach((item, index) => {
    if (yPos > 270) {
      doc.addPage();
      yPos = 20;
    }
    
    doc.text(`${index + 1}`, 20, yPos);
    doc.text(item.description.substring(0, 30), 30, yPos);
    doc.text(item.brand.substring(0, 15), 90, yPos);
    doc.text(item.model.substring(0, 12), 120, yPos);
    doc.text(`${item.qty}`, 145, yPos);
    doc.text(item.rate.toLocaleString(), 160, yPos);
    doc.text(item.amount.toLocaleString(), 190, yPos, { align: 'right' });
    yPos += 6;
  });

  yPos += 5;
  doc.setLineWidth(0.5);
  doc.line(20, yPos, 190, yPos);
  yPos += 10;

  // Totals
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.setFillColor(255, 237, 213); // Orange background
  doc.rect(20, yPos - 5, 170, 10, 'F');
  doc.text('Total Cost without Net-metering:', 25, yPos);
  doc.text(`PKR ${totals.withoutNetMetering.toLocaleString()}`, 190, yPos, { align: 'right' });
  yPos += 12;

  doc.setFillColor(220, 252, 231); // Green background
  doc.rect(20, yPos - 5, 170, 10, 'F');
  doc.text('Total Cost with Net-metering:', 25, yPos);
  doc.text(`PKR ${totals.withNetMetering.toLocaleString()}`, 190, yPos, { align: 'right' });
  yPos += 20;

  // Warranty Details
  if (yPos > 250) {
    doc.addPage();
    yPos = 20;
  }
  
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text('WARRANTY DETAILS', 20, yPos);
  yPos += 8;
  doc.setLineWidth(0.5);
  doc.line(20, yPos, 190, yPos);
  yPos += 10;

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text(`• ${warrantyDetails.solarPanelWarranty}`, 25, yPos);
  yPos += 8;
  doc.text(`• ${warrantyDetails.ongridInverterWarranty}`, 25, yPos);
  yPos += 8;
  doc.text(`• ${warrantyDetails.ongridInverterLocalWarranty}`, 25, yPos);
  yPos += 15;

  // Production Details
  if (yPos > 250) {
    doc.addPage();
    yPos = 20;
  }
  
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text('PRODUCTION & SAVINGS', 20, yPos);
  yPos += 8;
  doc.setLineWidth(0.5);
  doc.line(20, yPos, 190, yPos);
  yPos += 10;

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text(`Monthly Production: ${productionDetails.monthlyProduction.toLocaleString()} units`, 25, yPos);
  yPos += 8;
  doc.text(`Annual Production: ${productionDetails.annualProduction.toLocaleString()} units`, 25, yPos);
  yPos += 8;
  doc.text(`Annual Saving: PKR ${productionDetails.annualSaving.toLocaleString()}`, 25, yPos);
  yPos += 8;
  doc.text(`Backup Period: ${productionDetails.backupPeriod} years`, 25, yPos);
  yPos += 15;

  // Footer
  const pageCount = doc.internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(128, 128, 128);
    doc.text(
      `Generated by Solar CRM - solarhouse.pk | Page ${i} of ${pageCount}`,
      105,
      290,
      { align: 'center' }
    );
  }

  // Generate blob URL
  const pdfBlob = doc.output('blob');
  const url = URL.createObjectURL(pdfBlob);
  
  return url;
};
